# Generated by Django 4.2.10 on 2024-02-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustenuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treehacksuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
