# Generated by Django 4.2.10 on 2024-02-17 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustenuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('cost', models.FloatField(blank=True, max_length=2000)),
                ('item_type', models.FloatField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('location', models.CharField(blank=True, max_length=2000)),
                ('picture', models.CharField(blank=True, max_length=2000)),
                ('contact', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='treehacksuser',
            name='consumption_score',
            field=models.FloatField(default=0.0),
        ),
    ]
