# Generated by Django 4.2.10 on 2024-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustenuser', '0002_item_store_alter_treehacksuser_consumption_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageIntent',
        ),
        migrations.AddField(
            model_name='message',
            name='create_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
