# Generated by Django 4.2.10 on 2024-02-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustenuser', '0003_delete_messageintent_message_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_username', models.CharField(blank=True, max_length=2000)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='isRequest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_username',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
